## Name: Anuj thakre

## Roll. No: A-A2-20

## ML Lab

In [16]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import Standar
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import (accuracy_score, precision_score,
    recall_score, f1_score, classification_report, confusion_matrix,
    ConfusionMatrixDisplay)

pd.set_option('display.max_columns', None)

In [9]:
df = pd.read_csv('glass.csv')

In [10]:
df.head()

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [18]:
# Basic dataset overview
print("Dataset shape:", df.shape)

Dataset shape: (213, 10)

In [19]:

print("\nColumn names:")
print(df.columns.tolist())

Column names:
['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type']

In [20]:
print("\nDataset information:")
df.info()

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RI      213 non-null    float64
 1   Na      213 non-null    float64
 2   Mg      213 non-null    float64
 3   Al      213 non-null    float64
 4   Si      213 non-null    float64
 5   K       213 non-null    float64
 6   Ca      213 non-null    float64
 7   Ba      213 non-null    float64
 8   Fe      213 non-null    float64
 9   Type    213 non-null    int64
dtypes: float64(9), int64(1)
memory usage: 16.8 KB

In [12]:
# Check missing values and duplicate rows
print("Missing values in each column:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

df = df.drop_duplicates().reset_index(drop=True)

print("Shape after removing duplicates:", df.shape)

Missing values in each column:
RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

Duplicate rows: 1
Shape after removing duplicates: (213, 10)

In [14]:
# Statistical summary
df.describe()

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
count,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000,213.000000
mean,1.518348,13.404085,2.679202,1.449484,72.655070,0.498873,8.954085,0.175869,0.057277,2.788732
std,0.003033,0.816662,1.443691,0.495925,0.773998,0.653185,1.425882,0.498245,0.097589,2.105130
min,1.511150,10.730000,0.000000,0.290000,69.810000,0.000000,5.430000,0.000000,0.000000,1.000000
25%,1.516520,12.900000,2.090000,1.190000,72.280000,0.130000,8.240000,0.000000,0.000000,1.000000
50%,1.517680,13.300000,3.480000,1.360000,72.790000,0.560000,8.600000,0.000000,0.000000,2.000000
75%,1.519150,13.810000,3.600000,1.630000,73.090000,0.610000,9.150000,0.000000,0.100000,3.000000
max,1.533930,17.380000,4.490000,3.500000,75.410000,6.210000,16.190000,3.150000,0.510000,7.000000

# Count plot, Bar plot, Pie chart, histogram, Histogram + KDE, box plot, heatmap, scatter plot, pair plot, correlation matrix, IQR

In [25]:
label_encoder = LabelEncoder()

df["Class_encoded"] = label_encoder.fit_transform(df["Type"])

print(df[["Type", "Class_encoded"]].head(5))

   Type  Class_encoded
0     1              0
1     1              0
2     1              0
3     1              0
4     1              0

In [26]:
print("Class Mapping:")

for index, class_name in enumerate(label_encoder.classes_):
    print(index, "=", class_name)

Class Mapping:
0 = 1
1 = 2
2 = 3
3 = 5
4 = 6
5 = 7

In [28]:
numerical_features = df.select_dtypes(include=np.number).columns

print("Numerical Features:")
print(numerical_features.tolist())

Numerical Features:
['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type', 'Class_encoded']

In [29]:
numerical_features = df.select_dtypes(include=np.number).columns

In [42]:
X = df[numerical_features]
X = X.drop(columns=["Type", "Class_encoded"])

In [43]:
X.head()

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0

In [44]:
y = df["Class_encoded"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (213, 9)
y shape: (213,)

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

print("Training samples:", X_train.shape[0])
print("Testing sampels:", X_test.shape[0])

Training samples: 170
Testing sampels: 43

In [47]:
GaussianNB()

GaussianNB()

In [49]:
gnb = GaussianNB()

gnb.fit(X_train, y_train)

GaussianNB()

In [50]:
y_pred = gnb.predict(X_test)

print("Predicted labels:")
print(y_pred)

Predicted labels:
[5 1 0 3 0 0 0 1 0 0 0 0 5 4 0 5 5 0 0 1 0 0 5 0 2 0 1 4 1 0 3 0 0 5 0 0 1
 0 1 2 0 4 4]

In [52]:
comparison = pd.DataFrame({"Actual": y_test.values, "Predicted": y_pred})

print(comparison.head(5))

   Actual  Predicted
0       5          5
1       3          1
2       1          0
3       3          3
4       0          0

In [53]:
comparison["Actual_Class"] = label_encoder.inverse_transform(comparison["Actual"])

comparison["Predicted_Class"] = label_encoder.inverse_transform(comparison["Predicted"])

comparison.head(5)

   Actual  Predicted  Actual_Class  Predicted_Class
0       5          5             7                7
1       3          1             5                2
2       1          0             2                1
3       3          3             5                5
4       0          0             1                1

In [54]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Accuracy (%):", accuracy*100)

Accuracy: 0.5581395348837209
Accuracy (%): 55.81395348837209

In [56]:
precision = precision_score(y_test, y_pred, average='weighted')
print("Precision:", precision)

Precision: 0.5513440048323769

In [58]:
recall = recall_score(y_test, y_pred, average='weighted')
print("Recall:", recall)

Recall: 0.5581395348837209

In [60]:
f1 = f1_score(y_test, y_pred, average='weighted')
print("F1-Score:", f1)

F1-Score: 0.5190979563072586

In [61]:
print("======== MODEL PERFORMANCE ======")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1-Score  : {f1:.4f}")

======== MODEL PERFORMANCE ======
Accuracy  : 0.5581
Precision : 0.5513
Recall    : 0.5581
F1-Score  : 0.5191

In [67]:
print("Classification Report:\n")

print(classification_report(y_test, y_pred, target_names=label_encoder.classes_.astype(str)))

Classification Report:

              precision    recall  f1-score   support

           1       0.55      0.86      0.67        14
           2       0.57      0.27      0.36        15
           3       0.00      0.00      0.00         3
           5       0.50      0.33      0.40         3
           6       0.50      1.00      0.67         2
           7       0.83      0.83      0.83         6

    accuracy                           0.56        43
   macro avg       0.49      0.55      0.49        43
weighted avg       0.55      0.56      0.52        43

In [69]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[12  1  1  0  0  0]
 [ 7  4  1  0  2  1]
 [ 3  0  0  0  0  0]
 [ 0  2  0  1  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  1  0  5]]

In [70]:
from sklearn.metrics import accuracy_score

y_train_pred = gnb.predict(X_train)
y_test_pred = gnb.predict(X_test)

train_accuracy = accuracy_score(y_train, y_train_pred)

test_accuracy = accuracy_score(y_test, y_test_pred)

print("Training Accuracy :", train_accuracy)
print("Testing Accuracy  :", test_accuracy)

Training Accuracy : 0.5588235294117647
Testing Accuracy  : 0.5581395348837209

In [71]:
GaussianNB(priors=None)

GaussianNB()

## Main_Hyperparameters

In [72]:
GaussianNB(var_smoothing = 1e-9)

GaussianNB()

In [73]:
print(gnb.get_params())

{'priors': None, 'var_smoothing': 1e-09}

In [77]:
smoothing_values = [1e-12, 1e-10, 1e-9, 1e-8, 1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2]
results=[]

for value in smoothing_values:
    model = GaussianNB(var_smoothing=value)

    model.fit(X_train, y_train)
    prediction = model.predict(X_test)
    acc = accuracy_score(y_test,prediction)
    prec = precision_score(y_test,prediction, average='weighted')

    rec = recall_score(y_test, prediction, average='weighted')

    f1_value = f1_score(y_test, prediction, average='weighted')

    results.append([value, acc, prec, rec, f1_value])

/home/pro/Fifth Sem/ML/.venv/lib/python3.14/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [79]:
results_df = pd.DataFrame(
    results,
    columns = ["var_smoothing", "Accuracy", "Precision", "Recall", "F1-Score"]
)

results_df

   var_smoothing  Accuracy  Precision    Recall  F1-Score
0   1.000000e-12  0.558140   0.551344  0.558140  0.519098
1   1.000000e-10  0.558140   0.551344  0.558140  0.519098
2   1.000000e-09  0.558140   0.551344  0.558140  0.519098
3   1.000000e-08  0.558140   0.551344  0.558140  0.519098
4   1.000000e-07  0.558140   0.551344  0.558140  0.519098
5   1.000000e-06  0.511628   0.472194  0.511628  0.451498
6   1.000000e-05  0.511628   0.472194  0.511628  0.451498
7   1.000000e-04  0.534884   0.510148  0.534884  0.482835
8   1.000000e-03  0.534884   0.502427  0.534884  0.476969
9   1.000000e-02  0.558140   0.555251  0.558140  0.519151

In [80]:
print